In [1]:
import numpy as np

#行数の指定
ROW = 3

#正方行列の定義
A = np.array([[1,1,1],
              [2,3,-2],
              [3,-1,1]])
print(len(A))

#配列の初期化
L = np.zeros((ROW,ROW))
U = np.zeros((ROW,ROW))
Ai = np.zeros((ROW,ROW))

3


In [2]:
#LU分解（A=LUとなるような、左下三角行列Lと右上三角行列Uを求める）

Ai = np.copy(A)

for i in range(ROW):

    #LUに値を代入
    for k in range(ROW - i):
        L[ROW - (k + 1)][i] = Ai[ROW - (k + 1)][i]
        U[i][ROW - (k + 1)] = Ai[i][ROW - (k + 1)]/Ai[i][i]
        
        if i == (ROW - (k + 1)):
            U[i][ROW - (k + 1)] = 1
        
    #終了条件
    if (ROW - (i + 1)) == 0:
        break
        
    #＜アルゴリズム＞　Ai <-- Ai - l(1)*u(0)_T の変換はAi配列に直接変換値を代入している
    for j in range(ROW - (i + 1)):
        for m in range(ROW - (i + 1)):
            #Ai <-- Ai - l_1*u_T
            Ai[ROW - (1 + j)][ROW - (1 + m)] -=  L[ROW - (j + 1)][i]* U[i][ROW - (m + 1)]

print("L行列")
print(L)
print("\nU行列")
print(U)

L行列
[[  1.   0.   0.]
 [  2.   1.   0.]
 [  3.  -4. -18.]]

U行列
[[ 1.  1.  1.]
 [ 0.  1. -4.]
 [ 0.  0.  1.]]


In [3]:
#確認　LU --> A となるか

AA = np.zeros((ROW,ROW))

for i in range(ROW):
    for j in range(ROW):
        for k in range(ROW):
            AA[i][j] += L[i][k]*U[k][j]

print("元の行列")
print(A)
print("\nLUから戻した時のA行列")
print(AA)

元の行列
[[ 1  1  1]
 [ 2  3 -2]
 [ 3 -1  1]]

LUから戻した時のA行列
[[ 1.  1.  1.]
 [ 2.  3. -2.]
 [ 3. -1.  1.]]


In [4]:
# 3元連立方程式の解
# Xを求めたい行列とし、AX = Y で与えられた連立一元方程式を解く
# AX = Y --> UX = B, LB = Y で求まる

Y = np.array([9,5,7])

# LB = Y
B = np.zeros(ROW)

B[0] = Y[0]/L[0][0]
B[1] = Y[1]/L[1][1] - L[1][0] * B[0]/L[1][1]
B[2] = Y[2]/L[2][2] - L[2][1] * B[1]/L[2][2] - L[2][0] * B[0]/L[2][2]

#print(B)

# UX = B
X = np.zeros(ROW)

X[2] = B[2]
X[1] = B[1] - U[1][2] * X[2]
X[0] = B[0] - U[0][2] * X[2] - U[0][1] * X[1] 


print(方程式の解)
print(X)


[  9. -13.   4.]
[2. 3. 4.]


In [8]:
#一般解アルゴリズム
#AX = Y --> UX = B, LB = Y 

#ROW = 4
#Y = np.array([3,2,1,3])

Y = np.array([9,5,7])

#LB = Y
B = np.zeros(ROW)

for i in range(ROW):
    
    B[i] = Y[i]/L[i][i]
    if i == 0:
        continue
        
    for j in range(i):
        B[i] -= (L[i][i - j - 1]/L[i][i])*B[i - j - 1]

# UX = B
X = np.zeros(ROW)

for i in range(ROW):
    j = ROW - 1 - i
    
    X[j] = B[j]
    if i == 0:
        continue
    
    for k in range(i):
        X[j] -= U[j][ROW - (k + 1)]*X[ROW - (k + 1)]

        
print("\n方程式の解")
print(X)    
        
        
        


方程式の解
[2. 3. 4.]


In [10]:
ik = np.zeros((10,1))
print(ik)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
